In [55]:
import numpy as np
import pymatrix
def encryption():
  plaintext = ([15,0,24],
               [12,14,17],
               [4,12,14],
               [13,4,24])
  key = ([17,17,5],
         [21,18,21],
         [2,2,19])
  
  res = np.dot(plaintext,key)
  for i in range(0,len(res)):
    for j in range(0,len(res[i])):
      res[i][j] = (res[i][j])%26

  print("ENCRYPTED VALUE: ",res)
  decryption(res,key)

def decryption(res,key):
    adj = kinverse(res,key)
    decrypt = ([[4,9,15],[15,17,6],[24,0,17]])
    decr = np.dot(res,decrypt)%26
    print("DECRYPTED VALUE IS",decr)

def kinverse(res,key):
  det = np.linalg.det(key)
  modded = (int(det)%26)
  keypy = pymatrix.matrix([[17,17,5],[21,18,21],[2,2,19]])
  adj = keypy.adjoint()
  for i in range(0,len(key)):
    for j in range(0,len(key[i])):
      adj[i][j] = round((adj[i][j])%26)
  # mod inverse
  gcd,x,y= extended_gcd(modded,26)
  #x = mul inverse
  if x<0:
    x+=26
  for i in range(0,len(key)):
    for j in range(0,len(key[i])):
      adj[i][j] = (x*adj[i][j])%26
  return adj
  
def extended_gcd(a, b):
    if a == 0:
        return b, 0, 1
    else:
        gcd, x, y = extended_gcd(b % a, a)
        return gcd, y - (b // a) * x, x

encryption()

ENCRYPTED VALUE:  [[17 17 11]
 [12 22  1]
 [10  0 18]
 [15  3  7]]
DECRYPTED VALUE IS [[15  0 24]
 [12 14 17]
 [ 4 12 14]
 [13  4 24]]


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for pymatrix: filename=pymatrix-3.0.1-py3-none-any.whl size=7061 sha256=84518a079db2aab3a2ba28b2b9c72f89773842c1d1d256264bf18436c5de6313
  Stored in directory: /root/.cache/pip/wheels/0b/f6/fb/48658698ba9d602d6a134df6405d80ddc336c63585cf649bd0
Successfully built pymatrix
